AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/requests/*"
    - "spec/services/**/*"
Style/HashSyntax:
  Enabled: false
