AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/requests/*'
    - 'spec/services/**/*'
Metrics/MethodLength:
  Exclude:
    - 'app/controllers/*'
Style/HashSyntax:
  Enabled: false
